spring:
  mvc:
    problemdetails:
      enabled: true

  mongodb:
    uri: mongodb://root:wDbcVMMxovhTG5096NrYwippwrA-wf-bezZQKVzy6r53MNYf@ec7ce666-7a9b-473d-8306-168d27dad589.asia-southeast1.firestore.goog:443/db-eca?loadBalanced=true&tls=true&authMechanism=SCRAM-SHA-256&retryWrites=false

server:
  port: 0

eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
